-- Drop existing table if it exists
DROP TABLE IF EXISTS provider_reviews CASCADE;

-- Create provider_reviews table
CREATE TABLE provider_reviews (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    provider_id bigint REFERENCES providers(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    booking_id bigint REFERENCES bookings(id) ON DELETE CASCADE,
    rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
    review text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(booking_id)
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_provider_reviews_provider_id ON provider_reviews(provider_id);
CREATE INDEX IF NOT EXISTS idx_provider_reviews_user_id ON provider_reviews(user_id);

-- Enable RLS
ALTER TABLE provider_reviews ENABLE ROW LEVEL SECURITY;

-- Allow users to view reviews for providers they're interested in
CREATE POLICY "Anyone can view provider reviews"
ON provider_reviews FOR SELECT
USING (true);

-- Allow users to create reviews for their own bookings
CREATE POLICY "Users can create reviews for their bookings"
ON provider_reviews FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM bookings
        WHERE bookings.id = booking_id
        AND bookings.user_id = auth.uid()
        AND bookings.status = 'completed'
        AND NOT bookings.is_rated
    )
);

-- Allow users to update their own reviews
CREATE POLICY "Users can update their own reviews"
ON provider_reviews FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Allow users to delete their own reviews
CREATE POLICY "Users can delete their own reviews"
ON provider_reviews FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- Grant permissions
GRANT ALL ON provider_reviews TO authenticated;
GRANT USAGE ON SEQUENCE provider_reviews_id_seq TO authenticated;

-- Function to update provider rating
CREATE OR REPLACE FUNCTION update_provider_rating()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE providers
    SET rating = (
        SELECT AVG(rating)::decimal(3,2)
        FROM provider_reviews
        WHERE provider_id = NEW.provider_id
    ),
    total_ratings = (
        SELECT COUNT(*)
        FROM provider_reviews
        WHERE provider_id = NEW.provider_id
    )
    WHERE id = NEW.provider_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update provider rating
DROP TRIGGER IF EXISTS update_provider_rating_trigger ON provider_reviews;
CREATE TRIGGER update_provider_rating_trigger
AFTER INSERT OR UPDATE OR DELETE ON provider_reviews
FOR EACH ROW
EXECUTE FUNCTION update_provider_rating(); 