-- Create provider_reviews table
CREATE TABLE provider_reviews (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    provider_id bigint REFERENCES providers(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    booking_id bigint REFERENCES bookings(id) ON DELETE CASCADE,
    rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
    review text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(booking_id)
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_provider_reviews_provider_id ON provider_reviews(provider_id);
CREATE INDEX IF NOT EXISTS idx_provider_reviews_user_id ON provider_reviews(user_id);

-- Enable RLS
ALTER TABLE provider_reviews ENABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT ALL ON provider_reviews TO authenticated;
GRANT USAGE ON SEQUENCE provider_reviews_id_seq TO authenticated; 